// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIkoRPMCdjt6YSRKqpn1tvGDCE-6aShM',
    appId: '1:851597508701:web:788acfaf781a1ad90e4db4',
    messagingSenderId: '851597508701',
    projectId: 'online-class-32499',
    authDomain: 'online-class-32499.firebaseapp.com',
    storageBucket: 'online-class-32499.firebasestorage.app',
    measurementId: 'G-X93FHW2DYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVo8c6CrJxPRqCWtfcN2fCU2JZ6A67X3I',
    appId: '1:851597508701:android:5fdb098f7be678c80e4db4',
    messagingSenderId: '851597508701',
    projectId: 'online-class-32499',
    storageBucket: 'online-class-32499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE8ltp1_uBKu-n-LymGpdyji46MV9GCSc',
    appId: '1:851597508701:ios:8de636d59944424f0e4db4',
    messagingSenderId: '851597508701',
    projectId: 'online-class-32499',
    storageBucket: 'online-class-32499.firebasestorage.app',
    iosBundleId: 'com.example.onlineClass',
  );
}
